services:
  postgres:
    image: postgres:16.0
    container_name: pet_paradise_postgres
    environment:
      POSTGRES_DB: ${DEV_POSTGRES_DB}
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      TZ: "UTC-4"
    ports:
      - 3030:3030
    command: -p 3030
    profiles:
      - dev
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pet_paradise_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEV_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DEV_PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${DEV_PGADMIN_PORT}
    ports:
      - 4040:4040
    depends_on:
      - postgres
    profiles:
      - dev
    env_file:
      - .env

  backend:
    build: .
    ports:
      - 8000:80
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=80"
      - "prometheus.path=/metrics"

  prometheus:
    image: prom/prometheus:latest
    container_name: pet_paradise_prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    depends_on:
      - prometheus
